config/routes.rb
Rails.application.routes.draw do
  devise_for :users # devise Model(User)
  resources :bulletins do
    resources :posts
  end

  root 'welcome#index'

end

app/models/bulletin.rb
class Bulletin < ActiveRecord::Base
  has_many :posts, dependent: :destroy
end

app/models/post.rb
class Post < ActiveRecord::Base
  resourcify
  include Authority::Abilities
  belongs_to :bulletin
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  include Authority::UserAbilities
  has_many :posts, dependent: :destroy
  after_create :set_default_role, if: Proc.new { User.count > 1 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
  private

  def set_default_role
    add_role :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authority_forbidden(error)
    Authority.logger.warn(error.message)
    redirect_to request.referrer.presence || root_path, :alert => 'You are not authorized to complete that action.'
  end
end

app/controllers/bulletins_controller.rb
class BulletinsController < ApplicationController
  before_action :set_bulletin, only: [:show, :edit, :update, :destroy]

  # GET /bulletins
  # GET /bulletins.json
  def index
    @bulletins = Bulletin.all
  end

  # GET /bulletins/1
  # GET /bulletins/1.json
  def show
  end

  # GET /bulletins/new
  def new
    @bulletin = Bulletin.new
  end

  # GET /bulletins/1/edit
  def edit
  end

  # POST /bulletins
  # POST /bulletins.json
  def create
    @bulletin = Bulletin.new(bulletin_params)

    respond_to do |format|
      if @bulletin.save
        format.html { redirect_to @bulletin, notice: 'Bulletin was successfully created.' }
        format.json { render :show, status: :created, location: @bulletin }
      else
        format.html { render :new }
        format.json { render json: @bulletin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bulletins/1
  # PATCH/PUT /bulletins/1.json
  def update
    respond_to do |format|
      if @bulletin.update(bulletin_params)
        format.html { redirect_to @bulletin, notice: 'Bulletin was successfully updated.' }
        format.json { render :show, status: :ok, location: @bulletin }
      else
        format.html { render :edit }
        format.json { render json: @bulletin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bulletins/1
  # DELETE /bulletins/1.json
  def destroy
    @bulletin.destroy
    respond_to do |format|
      format.html { redirect_to bulletins_url, notice: 'Bulletin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bulletin
      @bulletin = Bulletin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bulletin_params
      params.require(:bulletin).permit(:title, :description, :post_type)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_bulletin
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [ :index, :show ]

  # GET /posts
  # GET /posts.json
  def index
    @posts = @bulletin.posts.all.order(created_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = @bulletin.posts.new
  end

  # GET /posts/1/edit
  def edit
    authorize_action_for @post
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = @bulletin.posts.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to bulletin_post_path(@post.bulletin, @post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    authorize_action_for @post
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to bulletin_post_path(@post.bulletin, @post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    authorize_action_for @post
    @post.destroy
    respond_to do |format|
      format.html { redirect_to bulletin_posts_url, notice: 'Post was successfully destroyed.' }#  notice: '~~' 이 부분이 flash 메세지
      format.json { head :no_content }
    end
  end

  private

    def set_bulletin
      @bulletin = Bulletin.find(params[:bulletin_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :picture, :picture_cache)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type
      when 'success'
        'alert-success'
      when 'error'
        'alert-danger'
      when 'alert'
        'alert-warning'
      when 'notice'
        'alert-info'
      else
        flash_type.to_s
    end
  end
  def user_roles(user)
    user.roles.map(&:name).join(',').titleize
  end
end

app/helpers/bulletins_helper.rb
module BulletinsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def bulletin_name(bulletin_id)
    Bulletin.find(bulletin_id).title
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bulletins/_form.html.erb
<%= simple_form_for(@bulletin) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :title %>
      <%= f.input :description, input_html: { rows: 5 } %>
      <%= f.input :post_type, collection: [ ['게시판', 'bulletin'], ['블로그', 'blog'], ['게임', 'game'] ] %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>

app/views/bulletins/edit.html.erb
<h2>Editing bulletin</h2>

<%= render 'form' %>

<hr>

<%= link_to 'Show', @bulletin, class: 'btn btn-default' %>
<%= link_to 'Back', bulletins_path, class: 'btn btn-default' %>

app/views/bulletins/index.html.erb
<h2>Bulletins</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Data actions</th>
    </tr>
  </thead>

  <tbody>
    <% @bulletins.each do |bulletin| %>
      <tr>
        <td><%= bulletin.title %></td>
        <td><%= bulletin.description %></td>
        <td>
          <%= link_to 'Show', bulletin, class: 'btn btn-default' %>
          <%= link_to 'Edit', edit_bulletin_path(bulletin), class: 'btn btn-default' %>
          <%= link_to 'Destroy', bulletin, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bulletin', new_bulletin_path, class: 'btn btn-default' %>

app/views/bulletins/new.html.erb
<h2>New bulletin</h2>

<%= render 'form' %>

<hr>

<%= link_to 'Back', bulletins_path, class: 'btn btn-default' %>

app/views/bulletins/show.html.erb
<h2>Preview Bulletin</h2>

<table class='table table-bordered'>
  <tr>
    <th>Title</th>
    <td><%= @bulletin.title %></td>
  </tr>
  <tr>
    <th>Description</th>
    <td><%= @bulletin.description %></td>
  </tr>
  <tr>
    <th>Created at</th>
    <td><%= @bulletin.created_at %></td>
  </tr>
  <tr>
    <th>Post Type</th>
    <td><%= @bulletin.post_type %></td>
  </tr>
</table>

<%= link_to 'Edit', edit_bulletin_path(@bulletin), class: 'btn btn-default' %>
<%= link_to 'Back', bulletins_path, class: 'btn btn-default' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auth Test</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag '/favicon.ico' %>
  <%= favicon_link_tag '/apple-icon-57x57.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= favicon_link_tag '/apple-icon-60x60.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= favicon_link_tag '/apple-icon-72x72.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= favicon_link_tag '/apple-icon-76x76.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= favicon_link_tag '/apple-icon-114x114.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= favicon_link_tag '/apple-icon-120x120.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= favicon_link_tag '/apple-icon-144x144.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= favicon_link_tag '/apple-icon-152x152.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= favicon_link_tag '/apple-icon-180x180.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= favicon_link_tag '/android-icon-192x192.png', rel: 'icon', type: 'image/png' %>
  <%= favicon_link_tag '/favicon-32x32.png', rel: 'icon', type: 'image/png' %>
  <%= favicon_link_tag '/favicon-96x96.png', rel: 'icon', type: 'image/png' %>
  <%= favicon_link_tag '/favicon-16x16.png', rel: 'icon', type: 'image/png' %>
  <%= favicon_link_tag '/manifest.json', rel: 'manifest' %>
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">
  <%= csrf_meta_tags %>
</head>
<body>
    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to raw("Auth<i>Test</i>"), root_path, class:'navbar-brand' %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="<%= params[:bulletin_id] == '1' ? 'active' : '' %>"><%= link_to '공지사항', bulletin_posts_path('1') %></li>
            <li class="<%= params[:bulletin_id] == '2' ? 'active' : '' %>"><%= link_to '새소식', bulletin_posts_path('2') %></li>
            <li class="<%= params[:bulletin_id] == '3' ? 'active' : '' %>"><%= link_to '가입인사', bulletin_posts_path('3') %></li>
            <li class="<%= params[:bulletin_id] == '4' ? 'active' : '' %>"><%= link_to '게임', bulletin_posts_path(4) %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %> <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "My Profile", edit_user_registration_path %></li>
                    <li><%= link_to "Roles : " + user_roles(current_user), '#' %></li>
                    <li><%= link_to "Sign out", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" } %></li>
                  </ul>
                </li>
            <% else %>
                <li><%= link_to "Sign in", new_user_session_path %></li>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      <%= render partial: 'shared/flash_messages', flash: flash %>

      <%= content_for?(:post_layout) ? content_for(:post_layout) : yield %>

    </div> <!-- /container -->
</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for([@bulletin, @post]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content, input_html: { rows: 10 } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h2><%= bulletin_name params[:bulletin_id] %></h2>
<div class="row">
  <div class='col-md-12'>
    <p style='text-align:right;'>
      created by <%= current_user.email %>, <%= time_ago_in_words(@post.created_at) %> ago
    </p>
  </div>
</div>
<%= render 'form' %>

<hr>
<%= link_to 'Show', [@post.bulletin, @post], class: 'btn btn-default' %>
<%= link_to 'Back', bulletin_posts_path, class: 'btn btn-default' %>

app/views/posts/index.html.erb
<%= render "posts/post_types/#{@bulletin.post_type}" %>

app/views/posts/new.html.erb
<h2><%= bulletin_name params[:bulletin_id] %></h2>
<div class="row">
  <div class='col-md-12'>
    <p style='text-align:right;'>
      created by <%= current_user.email %>, Current Time : <%= Time.now %>
    </p>
  </div>
</div>
<%= render 'form' %>

<hr>

<%= link_to 'Back', bulletin_posts_path, class: 'btn btn-default' %>

app/views/posts/post_types/_blog.html.erb
<h2><%= bulletin_name params[:bulletin_id] %> <small><%= link_to '설정', edit_bulletin_path(params[:bulletin_id])%></small></h2>

<% @posts.each do | post | %>
    <div class='post'>
      <div class='title'><%= post.title %></div>
      <div class='content'><%= simple_format post.content %></div>
      <div>
        <%= link_to 'Show', [post.bulletin, post], class:'btn btn-default' %>
        <% if user_signed_in? %>
            <% if post.updatable_by? current_user %>
                <%= link_to 'Edit', edit_bulletin_post_path(post.bulletin, post), class:'btn btn-default' %>
            <% end %>
            <% if post.deletable_by? current_user %>
                <%= link_to 'Destroy', [post.bulletin, post], method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-default' %>
            <% end %>
        <% end %>
      </div>
    </div>
<% end %>

<br>

<%= link_to 'New Post', new_bulletin_post_path, class: 'btn btn-default' %>

app/views/posts/post_types/_bulletin.html.erb
<h2><%= bulletin_name params[:bulletin_id] %> <small><%= link_to '설정', edit_bulletin_path(params[:bulletin_id])%></small></h2>

<table class="table">
  <thead>
  <tr>
    <th>Title</th>
    <th>Created by</th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @posts.each do |post| %>
      <tr>
        <td class="col-md-6 col-xs-6"><%= post.title %></td>
        <td><%= post.user.present? ? post.user.email : "n/a" %>, <%= time_ago_in_words(post.created_at) %> ago</td>
        <td>
          <%= link_to 'Show', [post.bulletin, post], class:'btn btn-default' %>
          <% if user_signed_in? %>
              <% if post.updatable_by? current_user %>
                  <%= link_to 'Edit', edit_bulletin_post_path(post.bulletin, post), class:'btn btn-default' %>
              <% end %>
              <% if post.deletable_by? current_user %>
                  <%= link_to 'Destroy', [post.bulletin, post], method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-default' %>
              <% end %>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Post', new_bulletin_post_path, class: 'btn btn-default' %>

app/views/posts/post_types/_game.html.erb
<h2>준비중입니다.</h2>

app/views/posts/show.html.erb
<h2><%= bulletin_name params[:bulletin_id] %></h2>

<div class='post'>
  <div class="title">
    <h3>Title:
      <%= @post.title %></h3>
  </div>

  <div class="content">
    <%= simple_format @post.content %>
  </div>

  <div class="user">
    <strong>Created by </strong>
    <%= @post.user.present? ? @post.user.email : "an anonymous user" %>,
    <%= time_ago_in_words(@post.created_at) %> ago
  </div>

  <!-- Like Button -->
  <div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
  </div>

</div>
<hr>
<%= link_to 'Edit', edit_bulletin_post_path(@post.bulletin, @post), class: 'btn btn-default' %>
<%= link_to 'Back', bulletin_posts_path, class: 'btn btn-default' %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> alert-dismissable fade in">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
<% end %>

app/views/welcome/index.html.erb
<h1>Rails Page</h1>
<p>Try Ruby on Rails</p>

<br>